title: Entry Web SDK
description: Documentation for the Entry Web SDK - secure biometric authentication
remote_theme: pages-themes/tactile@v0.2.0
plugins:
  - jekyll-remote-theme

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
